movie_rama/config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :users, except: :new
  resources :sessions, only: %i[create]
  resources :movie_reactions, only: %i[create update destroy]

  get "/signup", to: "users#new"

  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"

  root to: "movies#index"
end

movie_rama/app/controllers/movies_controller.rb
class MoviesController < SecureController
  before_action :set_reactions, except: :destroy

  def index
    i_params = index_params
    order = i_params[:order] || "date"
    dir = i_params[:dir] || "desc"
    @dir = dir == "desc" ? "asc" : "desc"
    @movies = Movie
      .includes(:user)
      .user(i_params[:user_id])
      .ordered(order, dir)
  end

  def show; end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new movie_params.merge(user: current_user)

    if @movie.save
      flash[:success] = "Movie #{@movie.title} created successfully"
      redirect_to movies_path
    else
      respond_to do |format|
        format.js { }
      end
    end
  end

  def edit; end

  def update
    if authorize_movie && @movie.update(movie_params)
      flash[:success] = "Movie #{@movie.title} created successfully"
      redirect_to movies_path
    else
      respond_to do |format|
        format.js { }
      end
    end
  end

  def destroy
    if authorize_movie && @movie.destroy
      flash[:success] = "Movie #{@movie.title} deleted successfully"
      redirect_to movies_path
    else
      flash[:error] = @movie.errors.messages
      render :destroy, status: 422
    end
  end

  private

  def index_params
    params.permit(:order, :dir, :user_id)
  end

  def movie_params
    params.require(:movie).permit(
      :title, :description, :user_id
    )
  end

  def set_reactions
    @reactions = Rails.cache.fetch("all_reactions") { Reaction.all }
  end

  def authorize_movie
    return true if @movie.user_id == current_user.try(:id)

    raise UnauthorizedException
  end
end

movie_rama/app/views/movies/_movie.html.haml
.movie
  .title
    = link_to movie.title, edit_movie_path(movie)
  .info
    %span.creator
      Shared by:&nbsp;
      = link_to movie.user_name, movies_path(params.permit(:order, :dir).merge(user_id: movie.user_id))
      = ", #{movie.created_since}"
  .description= movie.description
  .reactions{ id: movie.id }
    =render partial: 'movie_reactions_row', locals: { current_user: current_user, movie: movie, reactions: reactions }

movie_rama/app/views/movies/_movie_form.html.haml
- method = movie.id ? :put : :post
=form_with model: movie, remote: true, method: method, html: { id: 'movie-form' } do |f|
  %section
    =f.label :title, 'Title: '
    =f.text_field :title
    - if movie.errors[:title].any?
      %span.error=movie.errors[:title].join(', ')
  %section
    =f.label :description, 'Description: '
    =f.text_area :description, rows: 5
    - if movie.errors[:description].any?
      %span.error= movie.errors[:description].join(', ')
  =f.button('Save', type: 'submit')

movie_rama/app/views/movies/_movie_reactions_row.html.haml
:ruby
  user_movie_reaction = current_user.present? && current_user.check_reaction(movie_id: movie.id)
- reactions.each do |reaction|
  - style = reaction_span_style(user_movie_reaction, reaction)
  %span{ style: style }
    - if current_user && current_user.id != movie.user_id
      = reaction_link_to(reaction: reaction, user: current_user, movie: movie, umr: user_movie_reaction)
      %i= movie.reactions_count[reaction.name.to_sym] || 0
    - else
      %b{ title: current_user.present? ? "You cannot #{reaction.name} a movie you shared" : "Log in to #{reaction.name}"}
        ="#{reaction.name.pluralize.capitalize}: "
      %i= movie.reactions_count[reaction.name.to_sym] || 0

movie_rama/app/views/movies/_render_movie.js.erb
$("#movie-form").html(
  "<%= j render partial: "movie_form", locals: { movie: movie } %>"
);

movie_rama/app/views/movies/create.js.erb
<%= render partial: "render_movie", locals: { movie: @movie } %>

movie_rama/app/views/movies/edit.html.haml
.form-title
  %h2
    Update Movie
    =" #{@movie.title}"
.form
  =render partial: 'movie_form', locals: { movie: @movie }

movie_rama/app/views/movies/index.html.haml
.top-filters
  %span Sort By:
  %span
    - for_date = params[:order] == 'date'
    - dir = for_date ? @dir : 'desc'
    = link_to 'Date ', movies_path(params.permit(:user_id).merge(order: 'date', dir: dir)), class: for_date ? '' : 'margined'
    - if for_date
      = @dir == 'desc' ? material_icon.keyboard_arrow_up.md_18 : material_icon.keyboard_arrow_down.md_18
  - @reactions.each do |reaction|
    :ruby
      for_this_r = params[:order] == reaction.name
      dir = for_this_r ? @dir : 'desc'
      ordering_params = params.permit(:user_id).merge(
        order: reaction.name,
        dir: dir
      )
    %span
      = link_to "#{reaction.name.pluralize.capitalize}", ordering_params, class: for_this_r ? '' : 'margined'
      - if for_this_r
        = @dir == 'desc' ? material_icon.keyboard_arrow_up.md_18 : material_icon.keyboard_arrow_down.md_18
- @movies.each do |movie|
  = render partial: movie, locals: { current_user: current_user, reactions: @reactions }

movie_rama/app/views/movies/new.html.haml
.form-title
  %h2 New Movie
.form
  =render partial: 'movie_form', locals: { movie: @movie }

movie_rama/app/views/movies/update.js.erb
<%= render partial: "render_movie", locals: { movie: @movie } %>