movie_rama/config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :users, except: :new
  resources :sessions, only: %i[create]
  resources :movie_reactions, only: %i[create update destroy]

  get "/signup", to: "users#new"

  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"

  root to: "movies#index"
end

movie_rama/app/views/layouts/_header.html.haml
%header
  .title
    %h1
      =link_to 'MovieRama', root_path
  .profile
    - if current_user
      %span{class: 'btn'}="Welcome #{ current_user.full_name.split(' ').first }"
      =link_to "Log out", '/logout', class: 'btn btn-logout', method: :delete
      =link_to "+ Movie", new_movie_path, class: 'btn btn-new'
    - else
      =link_to 'Sign Up', signup_path, class: 'btn btn-signup'
      =link_to 'Login', login_path, class: 'btn btn-login'

movie_rama/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "https://fonts.googleapis.com/css2?family=Nunito:ital,wght@1,200&display=swap", :rel => "stylesheet"}/
    %title MovieRama
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header', locals: { current_user: current_user }
    - flash.each do |type, msg|
      %div{ class: "notification #{type}" }= msg
    %div.main
      = yield